/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ManeuverRouteImport } from './routes/maneuver'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ConjunctionsRouteImport } from './routes/conjunctions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjectNoradRouteImport } from './routes/object/$norad'
import { Route as ApiPublicTleRouteImport } from './routes/api/public/tle'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ManeuverRoute = ManeuverRouteImport.update({
  id: '/maneuver',
  path: '/maneuver',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ConjunctionsRoute = ConjunctionsRouteImport.update({
  id: '/conjunctions',
  path: '/conjunctions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectNoradRoute = ObjectNoradRouteImport.update({
  id: '/object/$norad',
  path: '/object/$norad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTleRoute = ApiPublicTleRouteImport.update({
  id: '/api/public/tle',
  path: '/api/public/tle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conjunctions': typeof ConjunctionsRoute
  '/connect': typeof ConnectRoute
  '/docs': typeof DocsRoute
  '/maneuver': typeof ManeuverRoute
  '/performance': typeof PerformanceRoute
  '/validation': typeof ValidationRoute
  '/object/$norad': typeof ObjectNoradRoute
  '/api/public/tle': typeof ApiPublicTleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conjunctions': typeof ConjunctionsRoute
  '/connect': typeof ConnectRoute
  '/docs': typeof DocsRoute
  '/maneuver': typeof ManeuverRoute
  '/performance': typeof PerformanceRoute
  '/validation': typeof ValidationRoute
  '/object/$norad': typeof ObjectNoradRoute
  '/api/public/tle': typeof ApiPublicTleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conjunctions': typeof ConjunctionsRoute
  '/connect': typeof ConnectRoute
  '/docs': typeof DocsRoute
  '/maneuver': typeof ManeuverRoute
  '/performance': typeof PerformanceRoute
  '/validation': typeof ValidationRoute
  '/object/$norad': typeof ObjectNoradRoute
  '/api/public/tle': typeof ApiPublicTleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conjunctions'
    | '/connect'
    | '/docs'
    | '/maneuver'
    | '/performance'
    | '/validation'
    | '/object/$norad'
    | '/api/public/tle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conjunctions'
    | '/connect'
    | '/docs'
    | '/maneuver'
    | '/performance'
    | '/validation'
    | '/object/$norad'
    | '/api/public/tle'
  id:
    | '__root__'
    | '/'
    | '/conjunctions'
    | '/connect'
    | '/docs'
    | '/maneuver'
    | '/performance'
    | '/validation'
    | '/object/$norad'
    | '/api/public/tle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConjunctionsRoute: typeof ConjunctionsRoute
  ConnectRoute: typeof ConnectRoute
  DocsRoute: typeof DocsRoute
  ManeuverRoute: typeof ManeuverRoute
  PerformanceRoute: typeof PerformanceRoute
  ValidationRoute: typeof ValidationRoute
  ObjectNoradRoute: typeof ObjectNoradRoute
  ApiPublicTleRoute: typeof ApiPublicTleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maneuver': {
      id: '/maneuver'
      path: '/maneuver'
      fullPath: '/maneuver'
      preLoaderRoute: typeof ManeuverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conjunctions': {
      id: '/conjunctions'
      path: '/conjunctions'
      fullPath: '/conjunctions'
      preLoaderRoute: typeof ConjunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object/$norad': {
      id: '/object/$norad'
      path: '/object/$norad'
      fullPath: '/object/$norad'
      preLoaderRoute: typeof ObjectNoradRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tle': {
      id: '/api/public/tle'
      path: '/api/public/tle'
      fullPath: '/api/public/tle'
      preLoaderRoute: typeof ApiPublicTleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConjunctionsRoute: ConjunctionsRoute,
  ConnectRoute: ConnectRoute,
  DocsRoute: DocsRoute,
  ManeuverRoute: ManeuverRoute,
  PerformanceRoute: PerformanceRoute,
  ValidationRoute: ValidationRoute,
  ObjectNoradRoute: ObjectNoradRoute,
  ApiPublicTleRoute: ApiPublicTleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
